/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockOne: typeof import('./src/components/asyncComponents/block-one.vue')['default']
    DatePicker: typeof import('./src/components/datePicker/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ErrorComp: typeof import('./src/components/asyncComponents/errorComp.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingComp: typeof import('./src/components/asyncComponents/loadingComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestPropsTip: typeof import('./src/components/Repackage/testPropsTip.vue')['default']
    VueDragResize: typeof import('./src/components/dragComponent/vue-drag-resize.vue')['default']
    XieInput: typeof import('./src/components/Repackage/XieInput.vue')['default']
  }
}
